### ISSUE TITLE
Building with libserial

### ISSUE THREAD

**Issue by pmkohn** [Legrandgroup/libezsp#56]
Hi, wanted to test out your libary, because its looking promising for my projekt, but if i try to compile it with libserial under linux following your readme i get:
mkohn@mkohn:~/libezsp$ make -j4
[  2%] Linking CXX shared library libezspspi.so
[ 74%] Built target ezsp
/usr/bin/ld: cannot find -lserialcpp
collect2: error: ld returned 1 exit status
src/spi/CMakeFiles/ezspspi.dir/build.make:302: recipe for target 'src/spi/libezspspi.so' failed
make[2]: *** [src/spi/libezspspi.so] Error 1

Have you renamed libserialcpp to libserial? Sadly i could not find the link in cmake. Would be nice if you could have a look.

**Comment by lionelains** [comment]
Hello

Yes, the libserial that libezsp depends on [is a fork](https://github.com/Legrandgroup/serial) of the official libserial.
In that fork, a custom makefile was created to simplify the build process, but it builds a `libserialcpp.so` library object instead of `libserial.so`.
Probably, the best way to fix this will be to update the custom makefile, but in the meantime, you can modify [this line](https://github.com/Legrandgroup/libezsp/blob/master/src/spi/CMakeLists.txt#L52) in `src/spi/CMakeLists.txt` so that it contains instead:
```
list(APPEND ezspspi_LIBS serial)
```

**Comment by pmkohn** [comment]
Thanks that was missing!
